# This file was generated by GoReleaser. DO NOT EDIT.
class Cosm < Formula
  desc "CLI tool for developing Cosmos SDK apps."
  homepage "https://github.com/allinbits/cosm"
  version "0.0.27"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/allinbits/cosm/releases/download/v0.0.27/cosm_0.0.27_darwin_amd64.tar.gz"
    sha256 "7fb69293b4d2d1503d6d44fc6e31382582b47107b8f16e23bac4512d5b99344b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/allinbits/cosm/releases/download/v0.0.27/cosm_0.0.27_linux_amd64.tar.gz"
      sha256 "90b547a2103670531b84b9c81f42491cf6aa88bf6ebc9beaa36ae54f00ffb67d"
    end
  end

  def install
    bin.install "cosm"
  end
end
